ela_image_uploader:
    resource: "@ElaImageUploaderBundle/Resources/config/routing.yml"
    prefix:   /

ela_host_editor:
    resource: "@ElaHostEditorBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"